.TH "LXNM" "1" 
.SH "NAME" 
lxnm \(em lightweight network manager 
.SH "SYNOPSIS" 
.PP 
\fBlxnm\fR 
.SH "DESCRIPTION" 
.PP 
This manual page documents briefly the 
\fBlxnm\fR command. 
.PP 
\fBlxnm\fR is a program that attempts 
to manage the network connections. It is script-based and make  
networking configuration and setup as painless and automatic as possible. 
 
.PP 
\fBlxnm\fR is the default Network Manager for LXDE project. 
It currently only works with netstat plugin of lxpanel. 
 
.SH "SEE ALSO" 
.PP 
lxpanel (1) 
.SH "AUTHOR" 
.PP 
This manual page was written by paulliu grandpaul@gmail.com for 
the \fBDebian\fP system (but may be used by others).  Permission is 
granted to copy, distribute and/or modify this document under 
the terms of the GNU General Public License, Version 2 any  
later version published by the Free Software Foundation. 
 
.PP 
On Debian systems, the complete text of the GNU General Public 
License can be found in /usr/share/common-licenses/GPL. 
 
.PP 
The source code of this manual page should be in  
\fB.sgml\fP format. It is better not to modify 
the \fB.1\fP file directly. 
 
.\" created by instant / docbook-to-man, Mon 05 May 2008, 22:51 
